import { Link, Route, Routes } from 'react-router-dom'

const phone = 'tel:+14693950360'
const services = [
  ['General Auto Repair','Diagnostics, maintenance and practical mechanical repairs.'],
  ['Exhaust Work','Exhaust inspection, muffler service and repair.'],
  ['Customer-Supplied Parts','Already bought the parts? Call to discuss installation.']
]

function Header(){return <header><Link className="logo" to="/"><b>M<span>&</span>S</b><i>MOTOR <span>&</span> SPORT<small>AUTO REPAIR</small></i></Link><nav><Link to="/">Home</Link><Link to="/services">Services</Link><Link to="/gallery">Gallery</Link><Link to="/about">About</Link><Link to="/contact">Contact</Link></nav><Link className="button red" to="/estimate">Free Estimate</Link></header>}
function Footer(){return <footer><div><Link className="logo" to="/"><b>M<span>&</span>S</b><i>MOTOR <span>&</span> SPORT<small>AUTO REPAIR</small></i></Link><p>Locally owned, family-operated auto repair in Garland, Texas.</p></div><div><h4>EXPLORE</h4><Link to="/services">Services</Link><Link to="/gallery">Gallery</Link><Link to="/about">About</Link></div><div><h4>CONTACT</h4><a href={phone}>(469) 395-0360</a><p>211 Barger St<br/>Garland, TX 75040</p></div></footer>}
function Shell({children}){return <><Header/>{children}<Footer/></>}
function PageHero({eyebrow,title,children}){return <section className="pageHero"><span>{eyebrow}</span><h1>{title}</h1><p>{children}</p></section>}
function CTA(){return <section className="cta"><div><small>NEED HELP WITH YOUR VEHICLE?</small><h2>LET'S GET YOU BACK ON THE ROAD.</h2></div><a className="button red" href={phone}>Call (469) 395-0360</a></section>}

function Home(){return <Shell><section className="hero"><div><span className="eyebrow">GARLAND'S LOCAL AUTO REPAIR SHOP</span><h1>BUILT FOR<br/>THE ROAD.<br/><em>READY FOR<br/>ANYTHING.</em></h1><p>Reliable mechanical work, exhaust service and honest help from a locally owned, family-operated shop.</p><div className="actions"><Link className="button red" to="/estimate">Get a Free Estimate</Link><a className="button outline" href={phone}>Call the Shop</a></div><div className="rating"><b>4.9</b><span>★★★★★</span><small>36 GOOGLE REVIEWS</small></div></div><div className="visual"><strong>M<span>&</span>S</strong><div className="car"><i/><i/></div></div></section><section className="section"><div className="title"><span>WHAT WE DO</span><h2>AUTOMOTIVE SERVICE<br/>WITHOUT THE RUNAROUND.</h2></div><div className="cards">{services.map((s,i)=><article key={s[0]}><small>0{i+1}</small><b>◆</b><h3>{s[0]}</h3><p>{s[1]}</p><Link to="/services">LEARN MORE →</Link></article>)}</div></section><section className="gallery dark"><div className="title"><span>INSIDE MOTOR & SPORT</span><h2>REAL WORK. REAL RESULTS.</h2></div><div className="photoGrid"><div className="photo wide">SHOP EXTERIOR</div><div className="photo">INSIDE THE GARAGE</div><div className="photo redPhoto">HANDS-ON SERVICE</div></div><Link className="button outline" to="/gallery">View the Gallery</Link></section><section className="faq section"><div className="title"><span>COMMON QUESTIONS</span><h2>GOOD TO KNOW<br/>BEFORE YOU VISIT.</h2></div><div>{[['Can I bring my own parts?','Yes. Call first so the team can confirm what is needed.'],['What work do you do?','General mechanical service and exhaust work.'],['Do I need an appointment?','Call to check current availability and hours.']].map((f,i)=><details key={f[0]} open={i===0}><summary>{f[0]}</summary><p>{f[1]}</p></details>)}</div></section><CTA/></Shell>}
function Services(){return <Shell><PageHero eyebrow="MOTOR & SPORT SERVICES" title="AUTO REPAIR DONE WITH PURPOSE.">Practical help, skilled work and direct communication from a neighborhood shop.</PageHero><section className="section serviceList">{services.map((s,i)=><article key={s[0]}><b>0{i+1}</b><div><h2>{s[0]}</h2><p>{s[1]}</p><a href={phone}>CALL TO DISCUSS THIS SERVICE →</a></div></article>)}</section><CTA/></Shell>}
function Gallery(){return <Shell><PageHero eyebrow="MOTOR & SPORT GALLERY" title="WORK FROM THE SHOP.">A look at the place, the vehicles and the hands-on work behind Motor & Sport.</PageHero><section className="section photoGrid pageGrid">{['Shop Exterior','Inside the Garage','Vehicle Service','Exhaust Work','Cars & Trucks','Ready for the Job'].map((x,i)=><div className={'photo '+(i===3?'redPhoto':'')} key={x}>{x}</div>)}</section><CTA/></Shell>}
function About(){return <Shell><PageHero eyebrow="ABOUT MOTOR & SPORT" title="A LOCAL SHOP BUILT ON REAL WORK.">Family-operated automotive service for Garland drivers who value direct answers and dependable repairs.</PageHero><section className="section story"><div className="storyVisual">M<span>&</span>S</div><div><span className="eyebrow">OUR STORY</span><h2>NEIGHBORS HELPING NEIGHBORS STAY ON THE ROAD.</h2><p>Motor & Sport is a locally owned, family-operated automotive facility at 211 Barger Street in Garland. The shop provides general mechanical services, exhaust work and installation using customer-supplied parts.</p></div></section><CTA/></Shell>}
function Contact(){return <Shell><PageHero eyebrow="CONTACT MOTOR & SPORT" title="TALK TO THE SHOP.">Call, visit or send an estimate request. We’ll help you figure out the right next step.</PageHero><section className="section contact"><div><small>PHONE</small><a href={phone}>(469) 395-0360</a><p>Call for today's hours and availability.</p></div><div><small>ADDRESS</small><a href="https://www.google.com/maps/search/?api=1&query=211+Barger+St+Garland+TX+75040">211 Barger St<br/>Garland, TX 75040</a><p>Open directions in Google Maps.</p></div><div><small>INSTAGRAM</small><a href="https://www.instagram.com/motorandsports1/">@motorandsports1</a><p>See shop updates and recent work.</p></div></section></Shell>}
function Estimate(){return <Shell><PageHero eyebrow="FREE ESTIMATE" title="TELL US WHAT'S GOING ON.">Start with a quick call. The shop will ask about your vehicle and help determine the next step.</PageHero><section className="section estimate"><div><h2>CALL MOTOR & SPORT</h2><p>Have your vehicle year, make, model and a short description of the problem ready.</p><a className="button red" href={phone}>Call (469) 395-0360</a></div><aside><h3>HELPFUL INFORMATION</h3><ul><li>Vehicle year, make and model</li><li>What you hear, feel or see</li><li>When the issue started</li><li>Parts already purchased</li></ul></aside></section></Shell>}
export default function App(){return <Routes><Route path="/" element={<Home/>}/><Route path="/services" element={<Services/>}/><Route path="/gallery" element={<Gallery/>}/><Route path="/about" element={<About/>}/><Route path="/contact" element={<Contact/>}/><Route path="/estimate" element={<Estimate/>}/></Routes>}
